[package]
name = "nu_plugin_handlebars"
version = "0.1.0"
authors = ["Idan Arye <IdanArye@gmail.com>"]
edition = "2024"
description = "An `handlebars` command for Nushell for rendering Nu values using Handlebars templates"
repository = "https://github.com/idanarye/nu_plugin_handlebars"
readme = "README.md"
keywords = ["nu", "plugin", "handlebars", "templating", "util"]
categories = ["command-line-utilities", "value-formatting", "template-engine"]
license = "MIT"

[dependencies]
dedent = "0.1.1"
handlebars = { version = "6.4.2", features = ["heck"] }
hashbrown = "0.17.1"
nu-plugin = "0.115.0"
nu-protocol = "0.115.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
typetag = "0.2"
uuid = { version = "1.23.4", features = ["serde", "v4"] }
